sudo: false
language: python
python:
- 2.6
- 2.7
- 3.2
- 3.3
- 3.4
- pypy
- pypy3
install:
- pip install -r requirements_test_runner.txt
- pip install -r requirements_static_analysis.txt
- pip install -r requirements_test.txt
- pip install coveralls
- python setup.py develop
before_script:
- flake8 setup.py "abduct"
- pyflakes setup.py "abduct"
script: nosetests --with-doctest --doctest-options="+NORMALIZE_WHITESPACE" --with-coverage --cover-tests --cover-inclusive --cover-package="abduct" "abduct"
after_success: coveralls
deploy:
  provider: pypi
  user: themattrix
  distributions: sdist bdist_wheel
  on:
    python: 2.7
    tags: true
    all_branches: true
    repo: themattrix/python-abduct
  password:
    secure: Aw81ZSHf1Rs1AcL25Fr8jj2E/C+TRC+GWZFHAjcqjTR8OE3TclB0yIXcgeCNdl+/i/Yjl7mPLyG4mJ7fckqRf1bLyasnWGFCBb84/c02Big5bVboCOlvgNQNTOr7p3+R1NCtQ3ZJ97BR4meQhdGLmAuN3vciHBNE+9TjGiNyRLc=
