language: python
env:
- TOXENV=py26
- TOXENV=py27
- TOXENV=py32
- TOXENV=py33
- TOXENV=py34
- TOXENV=pypy
- TOXENV=pypy3
install:
- pip install tox coveralls
script:
- tox
after_success:
- coveralls
deploy:
  provider: pypi
  user: themattrix
  distributions: sdist bdist_wheel
  on:
    python: 2.7
    tags: true
    all_branches: true
    repo: themattrix/python-abduct
  password:
    secure: Aw81ZSHf1Rs1AcL25Fr8jj2E/C+TRC+GWZFHAjcqjTR8OE3TclB0yIXcgeCNdl+/i/Yjl7mPLyG4mJ7fckqRf1bLyasnWGFCBb84/c02Big5bVboCOlvgNQNTOr7p3+R1NCtQ3ZJ97BR4meQhdGLmAuN3vciHBNE+9TjGiNyRLc=
